### ISSUE TITLE
Getting a 550

### ISSUE THREAD

**Issue by Mobilpadde** [niftylettuce/forward-email#7]
I've followed to tutorial stated on forwardemail.net, but whenever I try to send an email, I get this error: `550 Invalid forward-email TXT record`. Did I do something wrong? 

Records:

Name | TTL | Type | Priority | Value
-- | -- | -- | -- | --
cordes.rocks. | 3600 | TXT |   | v=spf1 a mx include:spf.forwardemail.net ~all
cordes.rocks. | 3600 | TXT |   | forward-email=charlotte:some@e.mail
cordes.rocks. | 3600 | TXT |   | forward-email=caroline:some@e.mail
cordes.rocks. | 3600 | TXT |   | forward-email=tommy:some@e.mail
cordes.rocks. | 3600 | TXT |   | forward-email=tina:some@e.mail
cordes.rocks. | 3600 | TXT |   | forward-email=mads:some@e.mail
cordes.rocks. | 3600 | MX | 20 | mx2.forwardemail.net.
cordes.rocks. | 3600 | MX | 10 | mx1.forwardemail.net.

**Comment by niftylettuce** [comment]
You need to only have one TXT record, see the example in the README, you need to join together with a comma your forwarding addresses `forward-email=hello:niftylettuce@gmail.com,support:niftylettuce@gmail.com`.

**Comment by Mobilpadde** [comment]
Oh, thanks!

**Comment by niftylettuce** [comment]
If you try again it should be fine.  Let me know otherwise!  If you want to forward me any rejections/issues/bounced mail you can at niftylettuce@gmail.com for me to further investigate.  I fixed quite a few issues recently.

**Comment by gustavengstrom** [comment]
I am also having problems with this. @niftylettuce by: only have one TXT record... Do you mean that both the SPF verification and forward-email settings should go into the same TXT record with a value such as: 

forward-email=name1:myname1@gmail.com,name2:myname2@gmail.com 
v=spf1 a mx include:spf.forwardemail.net -all

... or should these be in separate TXT records as outlined in @Mobilpadde's comment.

**Comment by gustavengstrom** [comment]
Thanks! I tested dig and every thing looks fine as far as I can tell... Here is the type of response I receive when running the later command. Does this response not mean that the changes have propagated and I should be able to send an email to name1@mydomain.com??

; <<>> DiG 9.10.6 <<>> mydomain.com txt
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1965
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mydomain.com.			IN	TXT

;; ANSWER SECTION:
mydomain.com.		3600	IN	TXT	"v=spf1 a mx include:spf.forwardemail.net ~all"
mydomain.com.		3600	IN	TXT	"forward-email=name1:myname1@gmail.com,name2:myname2@gmail.com"

**Comment by gustavengstrom** [comment]
@niftylettuce  I tested to send the mail from my hotmail account and it worked. It seems like the error is connected to the outlook account my workplace uses, since I still get an error when trying to send emails from there. It generates the following error:

Generating server: out10b.electric.net
name1@mydomain.com

mx1.forwardemail.net
Remote Server returned '554 5.0.0 <mx1.forwardemail.net #5.0.0 smtp; 550 Please ensure the email service you are sending from either has SPF or DKIM. You can most likely resolve this problem by searching on Google for "$serviceName SPF DKIM setup" (be sure to replace $serviceName with your email service provider, e.g. "Zoho").>'

**Comment by niftylettuce** [comment]
Should be good to go, lmk any issues. niftylettuce@gmail.com

**Comment by niftylettuce** [comment]
You need to setup SPF and DKIM on your domain.

**Comment by gustavengstrom** [comment]
Do you mean the domain I am sending the email from? If so this is clearly a problem since I have to alert all my potential contacts that they have to do this if they are getting a 554 response when attempting to send emails to me...

**Comment by niftylettuce** [comment]
Yes any of your contacts that are using custom domains and other services
should have SPF or DKIM at the very least setup on their domain for email
verification.  It's too easy otherwise to spoof as if someone was them.

**Comment by benyaminl** [comment]
Hello I also encounter same thing event the txt is right.

![image](https://user-images.githubusercontent.com/2817332/83354707-9a6bfb80-a384-11ea-8ce9-6214f835688d.png)
![image](https://user-images.githubusercontent.com/2817332/83354713-a22ba000-a384-11ea-867a-7cc9c7f970c5.png)


Any help apriciated. Thank you

**Comment by niftylettuce** [comment]
What is the 550?  You provided no details on the error itself.  You probably need to wait longer for NDS to propagate.  Wherever you are sending test mails from probably did not see the new MX servers set up on your domain yet.

**Comment by benyaminl** [comment]
> 
> 
> What is the 550? You provided no details on the error itself. You probably need to wait longer for DNS to propagate. Wherever you are sending test mails from probably did not see the new MX servers set up on your domain yet.

Sorry, I see the FAQ and tried to force clean the cache on Google and Cloudflare, and it works. Thank you for coming back here :)
